# Configuraci贸n de la base de datos
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbva
    username: root
    password: root
# Configuraci贸n de la aplicaci贸n
  jpa:
    hibernate:
      ddl-auto: update
# Configuraci贸n de la seguridad
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER