spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbva
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER