# Configuraci贸n de la base de datos
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db_springboot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# Configuraci贸n de la aplicaci贸n
  jpa:
    hibernate:
      ddl-auto: update
# Configuraci贸n de la seguridad
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER